<?php

function template_forgot_password ($data=null) {
    $htmlBody = '
    <table style="padding-top: 20px; background-color: rgb(234, 234, 234); background-image: url(&quot;https://ci3.googleusercontent.com/meips/ADKq_NY1kR9QuSQ0p3XO37t82mhxLwX4B629aBl6jISsS-yhiRf7994ZWNgmHZpxYqeYcfA-Qn8BxQDYD8VoW6xOwEGVAEei-3Uw8l64d3XoHTNyvIY=s0-d-e1-ft#https://www.twilio.com/resources/images/email/background.jpg&quot;); border: 0px; border-collapse: collapse; border-spacing: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-family: Whitney-SSm-A, Whitney-SSm-B, Whitney, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; line-height: 13px; margin: 0px; padding: 0px; text-align: center; vertical-align: baseline; min-width: 750px">
    <tbody style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
      <tr style="padding-top: 20px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
        <td style="margin: 0px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; padding: 0px; vertical-align: top;">
          <table style="background-color: rgb(255, 255, 255); border: 1px solid rgb(221, 221, 221); border-collapse: collapse; border-spacing: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px auto; max-width: 680px; padding: 0px; vertical-align: baseline; width: 680px;">
            <tbody style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
              <tr style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                <td align="left" style="margin: 0px; border-width: 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: initial; border-left-color: initial; border-image: initial; border-bottom-color: rgb(221, 221, 221); border-bottom-style: solid; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; padding: 0px; vertical-align: middle;">
                  <div style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 20px; padding: 0px; vertical-align: baseline;">
                    <img alt="otpus" class="CToWUd" data-bit="iit" jslog="138226; u014N:xr6bB; 53:WzAsMl0." src="https://cdn-icons-png.flaticon.com/512/733/733533.png" style="border: 0px none; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; outline: none; padding: 0px; vertical-align: baseline; width: 150px; height: 150px;" />
                  </div>
                </td>
              </tr>
              <tr style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                <td style="margin: 0px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; padding: 0px; vertical-align: middle;">
                  <table style="border: 0px; border-collapse: collapse; border-spacing: 0px; box-sizing: inherit; display: inline-block; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 10px 20px; vertical-align: baseline; width: unset;">
                    <tbody style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                      <tr style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                        <td style="margin: 0px; border-width: 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: initial; border-left-color: initial; border-image: initial; border-bottom-color: rgb(221, 221, 221); border-bottom-style: solid; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; padding: 0px; vertical-align: middle;">
                          <table style="border: 0px; border-collapse: collapse; border-spacing: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; max-width: 558px; padding: 0px; vertical-align: baseline; width: 558px;">
                            <tbody style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                              <tr style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                                <td align="left" style="margin: 0px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; height: 60px; padding: 0px; vertical-align: middle;">
                                  <p style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 20px; font-weight: bold; line-height: 20px; margin: 0px; padding: 0px; vertical-align: baseline;">OTP-US Change Password</p>
                                </td>
                              </tr>
                              <tr style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                                <td align="left" style="margin: 0px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; height: 50px; padding: 0px; vertical-align: middle;">
                                  <p style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 14px; line-height: 20px; margin: 0px; padding: 0px; vertical-align: baseline;">You need to click this link for changing your OTP-US Password.</p>
                                </td>
                              </tr>
                              <tr style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                                <td align="left" style="margin: 0px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; height: 60px; padding: 0px; vertical-align: middle;">
                                  <p style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 20px; font-weight: bold; line-height: 20px; margin: 0px; padding: 0px; vertical-align: baseline;">
                                    <a href="'.getenv('FE_DOMAIN_BASE_URL').'auth/new-password?token='.$data.'">Click here to Change Password.</a>
                                  </p>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                      <tr style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                        <td style="margin: 0px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; padding: 0px; vertical-align: middle;">
                          <table style="border: 0px; border-collapse: collapse; border-spacing: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; max-width: 558px; padding: 0px; vertical-align: baseline; width: 558px;">
                            <tbody style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                              <tr style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                                <td align="left" style="margin: 0px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; height: 50px; padding: 0px; vertical-align: middle;">
                                  <p style="border: 0px; box-sizing: inherit; font-variant: inherit; font-stretch: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 14px; line-height: 20px; margin: 0px; padding: 0px; vertical-align: baseline; font-style: italic;">The request for this access originated from OTP-US App</p>
                                </td>
                              </tr>
                              <tr style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                                <td align="left" style="margin: 0px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; height: 50px; padding: 0px; vertical-align: middle;">
                                  <p style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 14px; line-height: 20px; margin: 0px; padding: 0px; vertical-align: baseline;">In case you were not trying to access your OTP-US Account &amp; are seeing this email, please follow the instructions below:</p>
                                </td>
                              </tr>
                              <tr style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; padding: 0px; vertical-align: baseline;">
                                <td align="left" style="margin: 0px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; height: 10px; padding: 0px 0px 0px 20px; vertical-align: middle;">
                                  <ul style="border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; list-style-position: initial; list-style-image: initial; margin: 0px; padding: 0px; vertical-align: baseline;">
                                    <li style="margin: 0px 0px 5px 10px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 14px; line-height: 20px; padding: 0px; vertical-align: baseline;">
                                      <span class="il">Reset</span>&nbsp;your Twilio&nbsp; <span class="il">password</span>.
                                    </li>
                                    <li style="margin: 0px 0px 5px 10px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 14px; line-height: 20px; padding: 0px; vertical-align: baseline;">Check if any&nbsp; <span class="il">changes</span>&nbsp;were made to your account &amp; user settings. If yes, revert them immediately. </li>
                                    <li style="margin: 0px 0px 5px 10px; border: 0px; box-sizing: inherit; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-family: inherit; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 14px; line-height: 20px; padding: 0px; vertical-align: baseline;">If you are unable to access your OTP-US Account then contact OTP-US Support.</li>
                                  </ul>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
            </tbody>
          </table>
          <p>&nbsp;</p>
          <p>OTP-US</p>
        </td>
      </tr>
    </tbody>
  </table>
    ';

    return $htmlBody;
}